# cmake/EngineSources.cmake — shared engine-source-list logic.
#
# Extracted from web/CMakeLists.txt in Phase N Stage 0.1
# (WORKING/native-migration-plan-2026-09-04.md) so a future native/CMakeLists.txt can reuse it
# with its own per-target seam-exclude list (EDEN_NATIVE_SEAM_EXCLUDE, then EDEN_IOS_SEAM_EXCLUDE)
# instead of forking the read/filter logic. Callers own their own EDEN_*_SEAM_EXCLUDE list
# (each entry commented with WHY, not just what) and pass it in — this file only knows how to
# read tools/engine-sources.txt and apply whichever list it's given.

function(eden_collect_engine_sources)
  set(oneValueArgs OUT_VAR SOURCES_FILE BASE_DIR)
  set(multiValueArgs EXCLUDE_LIST)
  cmake_parse_arguments(EDEN_ECS "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  file(STRINGS "${EDEN_ECS_SOURCES_FILE}" _eden_sources_rel)

  set(_eden_sources "")
  foreach(rel IN LISTS _eden_sources_rel)
    if(rel MATCHES "^MISSING:")
      message(FATAL_ERROR "engine-sources.txt has an unresolved entry: ${rel} — regenerate with tools/gen-source-list.sh")
    endif()
    if(NOT rel IN_LIST EDEN_ECS_EXCLUDE_LIST)
      list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/${rel}")
    endif()
  endforeach()

  # --- Engine files added AFTER the 2.1.1 import ----------------------------------------------
  # tools/engine-sources.txt is generated by tools/gen-source-list.sh, which reads
  # Eden.xcodeproj's Sources build phase — so it can only ever list files the 2010-2014 project
  # knew about, and regenerating it would silently DROP anything added since. These go here
  # instead, where regeneration cannot touch them. They are ordinary engine code (../Classes/),
  # not seam or shim code, so every target wants them.
  #   Classes/MeshPool.mm — B3 Stage 2's off-thread mesher pool. pthreads + ordering semantics
  #   that belong next to Terrain; compiles to a set of no-ops without EDEN_THREADED.
  #   Classes/GLDialog.mm — Phase N Stage 2.5's engine GL modal (replaces the UIAlertViews for
  #   hosts with no native dialog layer). Inert on web: the DOM showAlert* seams never call it.
  #   Classes/GLWidgets.mm — Phase N Stage 5.1's GL widget kit (the design system in
  #   Graphics::drawRect fills). GLDialog is its first consumer; the Stage 5 screens follow.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/MeshPool.mm")
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/GLWidgets.mm")
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/GLDialog.mm")
  #   Classes/KeybindsMenu.mm — Phase N Stage 5.3's keybinds screen, the kit's second consumer.
  #   Driven from inside SettingsMenu, which web --wraps to a no-op, so it is inert there.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/KeybindsMenu.mm")
  #   Classes/WorldBrowser.mm — ROADMAP 5.9's Get Worlds screen (the community archive plus the
  #   current and legacy edengame.net servers) on the kit, over the eden_net_* seam. Inert on web:
  #   the seam's stubs report no network, so the menu never offers it there.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/WorldBrowser.mm")

  #   Classes/zstd/zstd.c — Stage S / S.2: zstd 1.5.7, single-file amalgamation WITHOUT the
  #   dictionary builder, threading or legacy decoders (tools/…/zstd-in.c recipe in
  #   docs/third-party.md). ONE pinned copy on every target, because byte-identical `.emod`
  #   output across targets depends on it (docs/emod-file-format.md). ASM off, and the
  #   strategies above level 3's (dfast) are compiled out, which is what keeps it ~150 KB of
  #   wasm. Level 19 is therefore tools-only (emod.py); the engine never encodes above 4.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/zstd/zstd.c")
  set_source_files_properties("${EDEN_ECS_BASE_DIR}/Classes/zstd/zstd.c" PROPERTIES
    COMPILE_DEFINITIONS "ZSTD_EXCLUDE_GREEDY_BLOCK_COMPRESSOR;ZSTD_EXCLUDE_LAZY_BLOCK_COMPRESSOR;ZSTD_EXCLUDE_LAZY2_BLOCK_COMPRESSOR;ZSTD_EXCLUDE_BTLAZY2_BLOCK_COMPRESSOR;ZSTD_EXCLUDE_BTOPT_BLOCK_COMPRESSOR;ZSTD_EXCLUDE_BTULTRA_BLOCK_COMPRESSOR")

  #   Classes/EdenWorldStore.cpp — Stage S / S.3: the `.emod` container (store + the forward-only
  #   .eden -> .emod converter). Plain C++, no ObjC, no engine globals; nothing in the game calls
  #   it until S.4, so web's linker drops it (and zstd with it) from a build without the self-test.
  #   Classes/EdenWorldStoreSelftest.cpp — its gates (eden_emod_selftest_run); the body compiles
  #   only with EDEN_DIAGNOSTICS, like the other self-tests.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/EdenWorldStore.cpp")
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/EdenWorldStoreSelftest.cpp")
  #   Classes/EdenWorldSource.cpp — Stage S / S.5: the raw `.eden` byte stream out of a plain file, a
  #   gzip or a zip, forward-only, so an archive converts to `.emod` while it inflates.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/EdenWorldSource.cpp")
  #   Classes/EdenWorldExport.cpp — Stage S / S.5 + S.5b: a world (`.emod` or `.eden`) as a pulled
  #   `.eden` / `.eden.gz` byte stream in a chosen format era, with the exact pre-flight + loss report.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/EdenWorldExport.cpp")
  #   Classes/WorldShare.mm — the GL menu's Share action (Export / Upload / Remove original) over it.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/WorldShare.mm")
  #   Classes/WorldTrailer.cpp — Stage D / D.3a: the post-directory trailer (signs, command blocks)
  #   as a model FileManager loads and saves on both containers. Plain C++, no engine globals.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/WorldTrailer.cpp")
  #   Classes/SignRenderer.mm — Stage D / D.3b: draws the trailer's signs in the 3D pass.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/SignRenderer.mm")
  #   Classes/SignTool.mm — Stage D / D.3c: the picker's SIGN tool and the anchor-removal rule.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/SignTool.mm")
  #   Classes/CmdScript.mm — Stage D / D.4c: the command-block interpreter (cmd.html's language).
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/CmdScript.mm")

  list(LENGTH _eden_sources_rel _eden_total_count)
  list(LENGTH _eden_sources _eden_kept_count)
  message(STATUS "Eden: ${_eden_kept_count} of ${_eden_total_count} engine sources kept (rest are seam-excluded, see the caller's *_SEAM_EXCLUDE list)")

  set(${EDEN_ECS_OUT_VAR} "${_eden_sources}" PARENT_SCOPE)
endfunction()
