# cmake/EngineSources.cmake — shared engine-source-list logic.
#
# Extracted from web/CMakeLists.txt in Phase N Stage 0.1
# (WORKING/native-migration-plan-2026-09-04.md) so a future native/CMakeLists.txt can reuse it
# with its own per-target seam-exclude list (EDEN_NATIVE_SEAM_EXCLUDE, then EDEN_IOS_SEAM_EXCLUDE)
# instead of forking the read/filter logic. Callers own their own EDEN_*_SEAM_EXCLUDE list
# (each entry commented with WHY, not just what) and pass it in — this file only knows how to
# read tools/engine-sources.txt and apply whichever list it's given.

function(eden_collect_engine_sources)
  set(oneValueArgs OUT_VAR SOURCES_FILE BASE_DIR)
  set(multiValueArgs EXCLUDE_LIST)
  cmake_parse_arguments(EDEN_ECS "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  file(STRINGS "${EDEN_ECS_SOURCES_FILE}" _eden_sources_rel)

  set(_eden_sources "")
  foreach(rel IN LISTS _eden_sources_rel)
    if(rel MATCHES "^MISSING:")
      message(FATAL_ERROR "engine-sources.txt has an unresolved entry: ${rel} — regenerate with tools/gen-source-list.sh")
    endif()
    if(NOT rel IN_LIST EDEN_ECS_EXCLUDE_LIST)
      list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/${rel}")
    endif()
  endforeach()

  # --- Engine files added AFTER the 2.1.1 import ----------------------------------------------
  # tools/engine-sources.txt is generated by tools/gen-source-list.sh, which reads
  # Eden.xcodeproj's Sources build phase — so it can only ever list files the 2010-2014 project
  # knew about, and regenerating it would silently DROP anything added since. These go here
  # instead, where regeneration cannot touch them. They are ordinary engine code (../Classes/),
  # not seam or shim code, so every target wants them.
  #   Classes/MeshPool.mm — B3 Stage 2's off-thread mesher pool. pthreads + ordering semantics
  #   that belong next to Terrain; compiles to a set of no-ops without EDEN_THREADED.
  #   Classes/GLDialog.mm — Phase N Stage 2.5's engine GL modal (replaces the UIAlertViews for
  #   hosts with no native dialog layer). Inert on web: the DOM showAlert* seams never call it.
  #   Classes/GLWidgets.mm — Phase N Stage 5.1's GL widget kit (the design system in
  #   Graphics::drawRect fills). GLDialog is its first consumer; the Stage 5 screens follow.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/MeshPool.mm")
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/GLWidgets.mm")
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/GLDialog.mm")
  #   Classes/KeybindsMenu.mm — Phase N Stage 5.3's keybinds screen, the kit's second consumer.
  #   Driven from inside SettingsMenu, which web --wraps to a no-op, so it is inert there.
  list(APPEND _eden_sources "${EDEN_ECS_BASE_DIR}/Classes/KeybindsMenu.mm")

  list(LENGTH _eden_sources_rel _eden_total_count)
  list(LENGTH _eden_sources _eden_kept_count)
  message(STATUS "Eden: ${_eden_kept_count} of ${_eden_total_count} engine sources kept (rest are seam-excluded, see the caller's *_SEAM_EXCLUDE list)")

  set(${EDEN_ECS_OUT_VAR} "${_eden_sources}" PARENT_SCOPE)
endfunction()
